services:
  db:
    image: postgres:17.5
    env_file:
      - prod.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    env_file:
      - prod.env
    ports:
      - "8001:8001"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        NEXT_PUBLIC_API_URL: http://localhost:8001
    command: npm start -- --port 80
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
