# Generated by Django 5.2.3 on 2025-06-18 01:32

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZakahCalculation',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Primary key for ZakahCalculation, generated as a UUID.', primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField(help_text='The calendar year the zakah calculation is associated with.', validators=[django.core.validators.MinValueValidator(1999), django.core.validators.MaxValueValidator(2999)])),
                ('month', models.PositiveSmallIntegerField(help_text='The calendar month of the zakah calculation (1-12).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='The total zakah amount calculated for the specified month and year.', max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('calculation_breakdown', models.JSONField(help_text="A structured JSON object detailing asset categories and their values, e.g., {'stocks': 5000, 'savings': 2000}.")),
                ('calculated_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of when the zakah was calculated and stored.')),
            ],
            options={
                'verbose_name': 'Zakah Calculation',
                'verbose_name_plural': 'Zakah Calculations',
                'db_table': 'zakah_calculation',
                'ordering': ['-year', '-month'],
                'indexes': [models.Index(fields=['year', 'month'], name='zakah_calcu_year_ac8d7e_idx')],
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='ZakahTransaction',
            fields=[
                ('payment_date', models.DateField(auto_created=True, help_text='The exact date on which the zakah payment was made.')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Primary key for ZakahTransaction, generated as a UUID.', primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='The monetary amount paid in this zakah transaction.', max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('paid_to', models.CharField(help_text='The recipient or organization to which this zakah was paid.', max_length=255)),
                ('payment_method', models.CharField(help_text='The payment method used to pay the zakah', max_length=127)),
                ('description', models.TextField(blank=True, help_text='Optional notes or comments related to the transaction (e.g., method of payment, purpose).', null=True)),
                ('zakah', models.ForeignKey(help_text='Reference to the associated zakah calculation instance.', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.zakahcalculation')),
            ],
            options={
                'verbose_name': 'Zakah Transaction',
                'verbose_name_plural': 'Zakah Transactions',
                'db_table': 'zakah_transaction',
                'ordering': ['-payment_date'],
                'indexes': [models.Index(fields=['payment_date'], name='zakah_trans_payment_eac24b_idx'), models.Index(fields=['paid_to'], name='zakah_trans_paid_to_b30fef_idx')],
            },
        ),
    ]
