# Generated by Django 5.2.3 on 2025-06-28 10:49

import django.core.validators
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Primary key for ZakahTransaction, generated as a UUID.', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='The amount of money/asset in this particular field.', max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'db_table': 'asset',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='asset_name_b9f5fe_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_lower_name')],
            },
        ),
    ]
