# Generated by Django 5.2.3 on 2025-06-29 00:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_asset'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['created_at'], 'verbose_name': 'Asset', 'verbose_name_plural': 'Assets'},
        ),
        migrations.AddField(
            model_name='asset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
